# Generated by Django 3.0.3 on 2020-09-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.BooleanField(choices=[('Approve', 'Approve'), ('Reject', 'Reject')], default=False)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.SellerProperty')),
            ],
        ),
    ]
