# Generated by Django 3.0.3 on 2020-09-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='request',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=10),
        ),
    ]
