# Generated by Django 3.0.3 on 2020-09-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20200927_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approve',
            old_name='request',
            new_name='request_approval',
        ),
    ]
