# Generated by Django 3.0.3 on 2020-09-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_sellerproperty_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproperty',
            name='image_house',
            field=models.ImageField(blank=True, null=True, upload_to='property'),
        ),
    ]
