# Generated by Django 3.0.3 on 2020-09-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20200927_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproperty',
            name='size',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
