# Generated by Django 3.0.3 on 2020-09-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_auto_20200927_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproperty',
            name='image_house',
            field=models.ImageField(default='property/c2.jpg', upload_to='property'),
        ),
    ]
