# Generated by Django 3.0.3 on 2020-09-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_auto_20200928_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='request_approval',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject'), ('Sold', 'Sold'), ('Pending', 'pending')], default='pending', max_length=10),
        ),
    ]
