# Generated by Django 3.0.3 on 2020-09-29 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_auto_20200929_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproperty',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
