# Generated by Django 3.0.3 on 2020-09-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_sellerproperty_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproperty',
            name='price',
            field=models.CharField(default='1 million', max_length=100),
        ),
    ]
