# Generated by Django 3.0.3 on 2020-09-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0016_auto_20200929_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerproperty',
            options={'ordering': ['-timestamp']},
        ),
    ]
