# Generated by Django 3.0.3 on 2020-09-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_auto_20200929_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerproperty',
            options={'ordering': ['timestamp']},
        ),
    ]
