# Generated by Django 3.0.3 on 2020-10-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0021_auto_20200930_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproperty',
            name='bedrooms',
            field=models.PositiveIntegerField(max_length=3),
        ),
    ]
