# Generated by Django 3.0.3 on 2020-10-02 22:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0026_auto_20201003_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproperty',
            name='bathroom',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('(\\d{999})$', 'Value less than 999 are allowed')]),
        ),
        migrations.AlterField(
            model_name='sellerproperty',
            name='bedrooms',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('(\\d{999})$', 'Value less than 999 are allowed')]),
        ),
        migrations.AlterField(
            model_name='sellerproperty',
            name='size',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator('(\\d{1000000})$', 'Value less than 1000000 are allowed')]),
        ),
    ]
