# Generated by Django 3.0.3 on 2020-10-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0030_auto_20201003_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproperty',
            name='bathroom',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sellerproperty',
            name='bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sellerproperty',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
